<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoService.Domain\AutoService.Domain.csproj" />
    <ProjectReference Include="..\AutoService.Contracts\AutoService.Contracts.csproj" />
    <ProjectReference Include="..\AutoService.Infrastructure.InMemory\AutoService.Infrastructure.InMemory.csproj" />
    <ProjectReference Include="..\AutoService.Application\AutoService.Application.csproj" />
  </ItemGroup>

</Project>
